name: Run News Scraper

on:
  schedule:
    - cron: "*/15 * * * *"  # Ejecuta cada 15 minutos
  workflow_dispatch:        # Permite ejecución manual desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraper
        run: |
          python main.py

      - name: Confirmar finalización
        run: echo "✅ Scraper ejecutado correctamente"
